language: node_js
node_js:
  - "12.4.0"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run-script coveralls
