export default {
	maj: 'maj',
	min: 'min',

	sus2: 'sus2',
	sus4: 'sus4',

	dim: 'dim',
	halfDim: 'halfDim',
	power: 'power',
	aug: 'aug',

	add2: 'add2',
	add4: 'add4',
	add6: 'add6',
	addb9: 'addb9',
	add9: 'add9',
	adds9: 'add#9',
	add11: 'add11',
	adds11: 'add#11',
	addb13: 'addb13',
	add13: 'add13',

	fifthFlat: 'b5',
	fifthSharp: '#5',
	seventhFlat: 'b7',
	seventh: '7',
	ninthFlat: 'b9',
	ninth: '9',
	ninthSharp: '#9',
	eleventh: '11',
	eleventhSharp: '#11',
	thirteenthFlat: 'b13',
	thirteenth: '13',
};
